# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colaboratory. 

Original file is located at
    https://colab.research.google.com/drive/1CYvbnZoem6LoeX9LEMt0fjYDahztcPbq
"""

print("------------------------------- Welcome to -------------------------------",
      "------------------------------ 10 Questions ------------------------------",
      "--- You must answer at least 5 questions correctly to win the contest. ---", sep= "\n")


def enterance():
  begin_contest = input("Do you want to begin the contest? (yes/no) ")
  while True:
    if begin_contest.lower() == "no":
      print("Good Bye, See You Next Time...")
      return
    elif begin_contest.lower() == "yes":
      contest()
      return
    else:
      begin_contest = input("Do you want to begin the contest? (yes/no) ")  

def contest():
  print("The contest is starting ...")
  
  CorrectAnswers = []
  WrongAnswers = []

  Question_1 = input("Where is the capital of Turkey? ")

  if Question_1.lower() == "ankara":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_2 = input("Which team is the Super League Champion of the 2019 - 2020 Season? ")

  if Question_2.lower() == "başakşehir":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_3 = input("What is the name of Mobile Operating System Developed by Google? ")

  if Question_3.lower() == "android":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_4 = input("How many colors are there in the rainbow? ")

  if Question_4.lower() == "7":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_5 = input("What is the largest country in the world? ")

  if Question_5.lower() == "russia":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_6 = input("Which Williams sister has won more Grand Slam titles? ")

  if Question_6.lower() == "serena":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_7 = input("Which email service is owned by Microsoft? ")

  if Question_7.lower() == "hotmail":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_8 = input("What part of the atom has no electric charge? ")

  if Question_8.lower() == "neutron":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_9 = input("Which planet is the hottest in the solar system? ")

  if Question_9.lower() == "venus":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  Question_10 = input("Which animal can be seen on the Porsche logo? ")

  if Question_10.lower() == "horse":
    print("Correct :) ")
    CorrectAnswers.append("C")
  else:
    print("Wrong :( ")
    WrongAnswers.append("W")

  print("You have " + str(CorrectAnswers.count("C")) + " Correct Answers")
  print("You have " + str(WrongAnswers.count("W")) + " Wrong Answers")
  Points = int(CorrectAnswers.count("C")) * 10
  print("You got " + str(Points) + " Points")

  if 5 <= CorrectAnswers.count("C"):
    print("Congratulations you won the contest !!!! :) ")
  else:
    print("Unfortunately, you lost the contest :( ")

enterance()
